import numpy as np
import matplotlib.pyplot as plt

reward_forward_data = np.load('reward_forward_data.npy')
reward_ctrl_data = np.load('reward_ctrl_data.npy')
action_data = np.load('action_data.npy')
tendon_data = np.load('tendon_data.npy')
oript_data = np.load('oript_data.npy')
iniyaw_data = np.load('iniyaw_data.npy')
waypt_data = np.load('waypt_data.npy')
x_pos_data = np.load('x_pos_data.npy')
y_pos_data = np.load('y_pos_data.npy')

# action_subdata = action_data * 0.25 + 0.40
action_subdata = action_data * 0.375 + 0.425
# action_subdata = action_data * 0.05 + 0.15
active_tendon_subdata = tendon_data[:,:6]
action_filted = np.zeros_like(action_subdata)
for i in range(action_subdata.shape[0]):
    if i == 0:
        action_filted[i] = 0.98 * active_tendon_subdata[i] + 0.02 * action_subdata[i]
    else:
        action_filted[i] = 0.98 * action_filted[i-1] + 0.02 * action_subdata[i]
plt.figure(figsize=(12, 4))
plt.subplot(611)
plt.plot(action_subdata[:,0], marker='.', linestyle='-')
plt.plot(active_tendon_subdata[:,0], linestyle='-')
plt.plot(action_filted[:,0], linestyle='--', color='red')
plt.ylabel('action subdata 0')
plt.grid()
plt.subplot(612)
plt.plot(action_subdata[:,1], marker='.', linestyle='-')
plt.plot(active_tendon_subdata[:,1], linestyle='-')
plt.plot(action_filted[:,1], linestyle='--', color='red')
plt.ylabel('action subdata 1')
plt.grid()
plt.subplot(613)
plt.plot(action_subdata[:,2], marker='.', linestyle='-')
plt.plot(active_tendon_subdata[:,2], linestyle='-')
plt.plot(action_filted[:,2], linestyle='--', color='red')
plt.ylabel('action subdata 2')
plt.grid()
plt.subplot(614)
plt.plot(action_subdata[:,3], marker='.', linestyle='-')
plt.plot(active_tendon_subdata[:,3], linestyle='-')
plt.plot(action_filted[:,3], linestyle='--', color='red')
plt.ylabel('action subdata 3')
plt.grid()
plt.subplot(615)
plt.plot(action_subdata[:,4], marker='.', linestyle='-')
plt.plot(active_tendon_subdata[:,4], linestyle='-')
plt.plot(action_filted[:,4], linestyle='--', color='red')
plt.ylabel('action subdata 4')
plt.grid()
plt.subplot(616)
plt.plot(action_subdata[:,5], marker='.', linestyle='-')
plt.plot(active_tendon_subdata[:,5], linestyle='-')
plt.plot(action_filted[:,5], linestyle='--', color='red')
plt.ylabel('action subdata 5')
plt.grid()

tendon_vel = np.diff(active_tendon_subdata, axis=0) / 0.02
ylim = [-0.25, 0.25]
plt.figure(figsize=(12, 4))
plt.subplot(611)
plt.plot(tendon_vel[:,0], linestyle='-')
plt.ylabel('tendon vel 0')
plt.ylim(ylim[0], ylim[1])
plt.grid()
plt.subplot(612)
plt.plot(tendon_vel[:,1], linestyle='-')
plt.ylabel('tendon vel 1')
plt.ylim(ylim[0], ylim[1])
plt.grid()
plt.subplot(613)
plt.plot(tendon_vel[:,2], linestyle='-')
plt.ylabel('tendon vel 2')
plt.ylim(ylim[0], ylim[1])
plt.grid()
plt.subplot(614)
plt.plot(tendon_vel[:,3], linestyle='-')
plt.ylabel('tendon vel 3')
plt.ylim(ylim[0], ylim[1])
plt.grid()
plt.subplot(615)
plt.plot(tendon_vel[:,4], linestyle='-')
plt.ylabel('tendon vel 4')
plt.ylim(ylim[0], ylim[1])
plt.grid()
plt.subplot(616)
plt.plot(tendon_vel[:,5], linestyle='-')
plt.ylabel('tendon vel 5')
plt.ylim(ylim[0], ylim[1])
plt.grid()

plt.figure(figsize=(5, 5))
vector_length = 1
iniyaw = iniyaw_data[0]
vec_endpt = oript_data + vector_length * np.array([np.cos(iniyaw), np.sin(iniyaw)])
plt.plot([oript_data[0], vec_endpt[0]], [oript_data[1], vec_endpt[1]], 'r-', label='forward direction')
plt.scatter([oript_data[0]], [oript_data[1]], color='blue', label='original point')
plt.scatter([waypt_data[:, 0]], [waypt_data[:, 1]], color='green', label='waypoint')
plt.plot(x_pos_data, y_pos_data, marker='.', markersize=3)
plt.axis('equal')
plt.title('x-y position')
plt.xlabel('x')
plt.ylabel('y')
plt.grid()
plt.show()

